apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-html-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <title>Simple HTML App</title>
      </head>
      <body>
        <h1>Hello from Kubernetes!</h1>
      </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-html-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-html
  template:
    metadata:
      labels:
        app: simple-html
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: html-volume
        configMap:
          name: simple-html-config
---
apiVersion: v1
kind: Service
metadata:
  name: simple-html-service
spec:
  type: NodePort
  selector:
    app: simple-html
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080 